<%@ include file="/init.jsp"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<%@ taglib uri="http://java.sun.com/portlet_2_0" prefix="portlet" %>

<%@ taglib uri="http://liferay.com/tld/aui" prefix="aui" %><%@
taglib uri="http://liferay.com/tld/portlet" prefix="liferay-portlet" %><%@
taglib uri="http://liferay.com/tld/theme" prefix="liferay-theme" %><%@
taglib uri="http://liferay.com/tld/ui" prefix="liferay-ui" %>

<liferay-theme:defineObjects />

<portlet:defineObjects />

<%-- <portlet:actionURL name="accountStatement" var="accountStatementUrl"></portlet:actionURL> --%>
<portlet:resourceURL id="/accountStatement/save" var="accountStatementUrl"></portlet:resourceURL>
<portlet:resourceURL id="/rejectionreturn/getreportlogdetails" var="getreportlogdetailsURL"></portlet:resourceURL>
		<style>
			.modal {
			    display: none;
			}
		</style>
		
		<div class="modal fade" id="success_tic" tabindex="-1" aria-labelledby="success_ticLabel" aria-hidden="true">
		  <div class="modal-dialog modal-sm">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
		      </div>
		      <div class="modal-body text-center">
		      	<i class="fas fa-check-circle text-success fa-4x d-block mb-4"></i>      
		        Data sent for Review.
		      </div>       
		    </div>
		  </div>
		</div>
		<div class="modal fade" id="errorExcel" tabindex="-1" aria-labelledby="success_ticLabel" aria-hidden="true">
		  <div class="modal-dialog modal-sm">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
		      </div>
		      <div class="modal-body text-center text-danger">
		      	<i class="fas fa-times-circle  fa-4x d-block mb-4"></i>      
		        <span id="output"></span>
		      </div>       
		    </div>
		  </div>
		</div>
 <div class="nps-page-main nps-upload-report nps-statement-wrapper">
 
  <div class="row mb-3">
         <div class="col-12">
            <div class="text-right">
                 <p  class="back_btn"><a class="backbtn" href="/web/guest/monthly-average"><i class="fas fa-arrow-left text-white pr-3"></i>Back</a></p>
            </div>
         </div>
    </div>
    
	<div class="row">
	    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
	        <div class="nps-report">
	            <h4>Monthly Account Statements</h4>
	            <form class="form row" method="post">
	            	<input type="hidden" name="dlfileid"/>
					<input type="hidden" name="<portlet:namespace/>reportUploadLogId" class="reportUploadLogId"/>
					<input type="hidden" value="24" name="<portlet:namespace/>reportMasterId" class="reportMasterId"/>
	            	<div class="col-lg-6 col-md-6 col-sm-12 col-12">
                         <div class="nps-input-box mt-0">
                             <label for="name">Report Due Date</label>
                             <input class="reportDate" type="date" readonly="readonly">
                         </div>
                     </div>
<%-- 	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="accountname">Account Name</label>
	                        <input type="text" id="accountname" name="<portlet:namespace/>accountname" placeholder="Account Name" required>
	                    	<label class="error" for="<portlet:namespace/>accountname"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="statement">Statement Generated By</label>
	                        <input type="text" id="statement" name="<portlet:namespace/>statement" placeholder="Statement Generated By" required>
	                        <label class="error" for="<portlet:namespace/>statement"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="customerno">Customer No.</label>
	                        <input type="text" id="customerno" name="<portlet:namespace/>customerno" placeholder="Customer No." required>
	                        <label class="error" for="<portlet:namespace/>customerno"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="scheme">Scheme</label>
	                        <input type="text" id="scheme" name="<portlet:namespace/>scheme" placeholder="Scheme" required>
	                        <label class="error" for="<portlet:namespace/>scheme"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="currency">Currency:INR</label>
	                        <input type="text" id="currency" name="<portlet:namespace/>curencyinr" placeholder="Currency:INR" required>
	                        <label class="error" for="<portlet:namespace/>curencyinr"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="adressi">Address Line-1</label>
	                        <input type="text" id="adressi" name="<portlet:namespace/>adressi" placeholder="Address Line-1" required>
	                        <label class="error" for="<portlet:namespace/>adressi"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="adressii">Address Line-2</label>
	                        <input type="text" id="adressii" name="<portlet:namespace/>adressii" placeholder="Address Line-2" required>
	                        <label class="error" for="<portlet:namespace/>adressii"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="adressiii">Address Line-3</label>
	                        <input type="text" id="adressiii" name="<portlet:namespace/>adressiii" placeholder="Address Line-3" required>
	                        <label class="error" for="<portlet:namespace/>adressiii"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="adressiv">Address Line-4</label>
	                        <input type="text" id="adressiv" name="<portlet:namespace/>adressiv" placeholder="Address Line-4" required>
	                        <label class="error" for="<portlet:namespace/>adressiv"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="adressv">Address Line-5</label>
	                        <input type="text" id="adressv" name="<portlet:namespace/>adressv" placeholder="Address Line-5" required>
	                        <label class="error" for="<portlet:namespace/>adressv"></label>
	                    </div>
	                </div>
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="pin">PIN</label>
	                        <input type="text" id="pin" name="<portlet:namespace/>pin" placeholder="PIN" required>
	                        <label class="error" for="<portlet:namespace/>pin"></label>
	                    </div>
	                </div>
	
	                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                    <div class="nps-input-box mt-0">
	                        <label for="accountno">Statement of Account No:</label>
	                        <input type="text" id="accountno" name="<portlet:namespace/>statementacno" placeholder="Statement of Account No:" required>
	                        <label class="error" for="<portlet:namespace/>statementacno"></label>
	                    </div>
	                </div>
	                <div class="col-lg-12">
	                    <h4 class="px-0 py-2 border-bottom-0">For the Period of</h4>
	                    <div class="row">
	                        <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                            <div class="nps-input-box mt-0">
	                                <label for="from">From:</label>
	                                <input type="date" id="form" name="<portlet:namespace/>formdate" required>
	                            </div>
	                        </div>
	                        <div class="col-lg-6 col-md-6 col-sm-12 col-12">
	                            <div class="nps-input-box mt-0">
	                                <label for="to">To:</label>
	                                <input type="date" id="to" name="<portlet:namespace/>todate" required>
	                            </div>
	                        </div>
	                    </div>
	                </div> --%>
					<div class="row">
			                  <div class="col-lg-6 col-md-6 col-sm-12 col-12">
			                     <div class="nps-input-box file-upload">
			                        <div class="nps-input-box mt-0">
			                           <label>Annexure 2</label>
			                           <div class="file-select">
			                              <div class="file-select-name" id="noFile1">File Name</div>
			                              <div class="file-select-button common-btn" id="fileName">Choose File</div>
			                              <input type="file" class="annexure2" id="annexure2" name="annexure2" accept=".pdf"/>
			                           </div>
			                           <label id="error1" class="error-message text-danger"></label>
			                           <br>
			                        </div>
			                     </div>
			                  </div>
		<%-- 	                  <div class="col-lg-6 col-md-6 col-sm-12 col-12">
			                  	<div class="form-group">
		                        	<textarea class="form-control" id="board_a_rem" placeholder="Remarks if any" name="board_a_rem_intermediarys" ><%= (Validator.isNotNull(inputQuarterlyInterval))? inputQuarterlyInterval.getBoard_b_rem():"" %></textarea>
		                        </div>
			                  </div> --%>
		                 </div>
		                 
	                <%-- <div class="statement-wrapper">
	                    <div id="table" class="table-editable">
	                    <div class="text-end">
	                     		<button id="addRow" class="common-btn d-inline-block table-add glyphicon glyphicon-plus text-capitalize mb-3 mt-md-0 mt-sm-3 mt-3" type="button">Add Row</button>
	                            <!-- <a href="javascript:;"
	                                class="common-btn d-inline-block table-add glyphicon glyphicon-plus text-capitalize mb-3 mt-md-0 mt-sm-3 mt-3">Add
	                                Row</a> -->
                        </div>
                		<input type="hidden" class="rowcount" name="<portlet:namespace />rowcount">
                        <div class="table-cont" > 
                            <table class="table" id="example">
                                <thead>
                                    <tr>
                                        <th>TRan Date</th>
                                        <th>Chq No</th>
                                        <th>Particulars</th>
                                        <th>Debit</th>
                                        <th>Credit</th>
                                        <th>Balance</th>
                                        <th>Init.Br.</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
				                        <td></td>
				                        <td></td>
				                        <th>Opening Balance</th>
				                        <td></td>
				                        <td></td>
				                        <td></td>
				                        <td></td>
				                        <td></td>
				                    </tr>
				                    <tr>
				                        <td><input type="date" class="tRandate form-control" name="<portlet:namespace />trandate1"></td>
				                        <td><input type="text" class="chqno form-control" name="<portlet:namespace />chqno1"></td>
				                        <td><input type="text" class="particulars form-control" name="<portlet:namespace />particulars1"></td>
				                        <td><input type="text" class="debit form-control" name="<portlet:namespace />debit1"></td>
				                        <td><input type="text" class="credit form-control" name="<portlet:namespace />credit1"></td>
				                        <td><input type="text" class="balance form-control" name="<portlet:namespace />balance1"></td>
				                        <td><input type="text" class="initbr form-control" name="<portlet:namespace />initbr1"></td>
				                        <td></td>
				                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td rowspan="1" colspan="1"></td>
                                        <td rowspan="1" colspan="1"></td>
                                        <th rowspan="1" colspan="1">Transaction Total</th>
                                        <td>
                                            <input type="text" class="todebit form-control" name="<portlet:namespace />todebit">
                                        </td>
                                        <td>
                                            <input type="text" class="tocredit form-control" name="<portlet:namespace />tocredit">
                                        </td>
                                        <td rowspan="1" colspan="1"></td>
                                        <td rowspan="1" colspan="1"></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td rowspan="1" colspan="1"></td>
                                        <td rowspan="1" colspan="1"></td>
                                        <th colspan="1" rowspan="1">Closing Balance</th>
                                        <td></td>
                                        <td></td>
                                        <td rowspan="1" colspan="1">
                                            <input type="text" class="clbalance form-control" name="<portlet:namespace />clbalance">
                                        </td>
                                        <td rowspan="1" colspan="1">
                                            <input type="text" class="clinitbr form-control" name="<portlet:namespace />clinitbr">
                                        </td>
                                        <td></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div> --%>

                <div class="nps-input-box">
                	<button id="btn-submit" class="common-btn d-inline-block" name="Submit" type="button" >Save</button>
                </div>
              </form>
            </div>
        </div>
    </div>
</div>
  
	<div class="animaion" style="display:none;">
	 	<div class="row">
			<div class="loading-animation"></div>
		</div>
	</div>

	<style>
	input.error {
		border:1px solid red !important;
	}
	
	
	/* label.error {
		display: none !important;
	}  */
	</style>
               
<%-- <div class="card_blocks">
    <div class="row">
        <div class="col">
            <div class="page_title">
                <img src="<%=request.getContextPath()%>/images/contact-form-title.png" alt="Upload Reports" /> Annexure2-Format of Account Statement
            </div>
        </div>
    </div> --%>

  <%-- <div class="nps-body-main">
    <div class="nps-page-main nps-upload-report">
        <div class="row">
            <div class="col-lg-7 col-md-10 col-sm-12 col-12">
                <div class="nps-report">
        		<h4>Annexure2-Format of Account Statement</h4>
            	<aui:form id="myForm" method="post">
	            	<input type="hidden" name="dlfileid"/>
					<input type="hidden" name="<portlet:namespace/>reportUploadLogId" class="reportUploadLogId"/>
					<input type="hidden" value="24" name="<portlet:namespace/>reportMasterId" class="reportMasterId"/>
					<div class="row">
		               	<div class="nps-input-box mt-0">
	                        <label for="name">Report Due Date</label>
	                        <input class="reportDate" type="date" readonly="readonly">
	                     </div>
		            </div>
	                <div class="row">
	                    <div class="col-md-4 pt-3">
	                        <div class="form-group">
	                            <!-- <label style="font-size: 15px;">Account Name:</label> -->
	                            <input type="text" class="account-name form-control" placeholder="Account Name:" name="<portlet:namespace />accountname">
	                            <label class="error" for="<portlet:namespace/>accountname"></label>
	                        </div>
	                    </div>
	                    <div class="col-md-8">
	                        <div class="form-group">
	                        </div>
	                    </div>
	                </div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <input type="text" class="statement form-control" placeholder="Statement Generated By:" name="<portlet:namespace />statement">
                        </div>
                        <label class="error" for="<portlet:namespace/>statement"></label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="row">
                                <div class="col">
                                    <input type="text" class="adress-1 form-control" placeholder="Adress Line-1" name="<portlet:namespace />adressi">
                                    <label class="error" for="<portlet:namespace/>adressi"></label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col pt-3">
                                    <input type="text" class="adress-2 form-control" placeholder="Adress Line-2" name="<portlet:namespace />adressii">

                                </div>
                            </div>
                            <div class="row">
                                <div class="col pt-3">
                                    <input type="text" class="adress-3 form-control" placeholder="Adress Line-3" name="<portlet:namespace />adressiii">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col pt-3">
                                    <input type="text" class="adress-4 form-control" placeholder="Adress Line-4" name="<portlet:namespace />adressiv">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col pt-3">
                                    <input type="text" class="adress-5 form-control" placeholder="Adress Line-5" name="<portlet:namespace />adressv">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col pt-3">
                                    <input type="text" class="pin form-control" placeholder="PIN" name="<portlet:namespace />pin">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group"></div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="row ">
                                <div class="col pt-3">
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col pt-3">
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col pt-3">
                                    <input type="text" class="customer no form-control" placeholder="Customer No." name="<portlet:namespace />customerno">
                                    <label class="error" for="<portlet:namespace/>customerno"></label>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col pt-3">
                                    <input type="text" class="scheme no form-control" placeholder="Scheme:" name="<portlet:namespace />scheme">
                                    <label class="error" for="<portlet:namespace/>scheme"></label>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col pt-3">
                                    <input type="text" class="currency-inr form-control" placeholder="Currency:INR" name="<portlet:namespace />curencyinr">
                                    <label class="error" for="<portlet:namespace/>curencyinr"></label>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col pt-3">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label style="font-size: 15px;">Statement of Account No:</label>
                            <input type="text" class="Statement form-control" name="<portlet:namespace />statementacno">
                        </div>
                        <label class="error" for="<portlet:namespace/>statementacno"></label>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <label style="font-size: 15px;">For the Period of:</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label style="font-size: 15px;">Form:</label>
                            <input type="date" class="formdate form-control" placeholder="Form:yyyy-mm-dd" name="<portlet:namespace />formdate">
                        </div>
                        <label class="error" for="<portlet:namespace/>formdate"></label>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label style="font-size: 15px;">To:</label>
                            <input type="date" class="todate form-control" placeholder="To:yyyy-mm-dd" name="<portlet:namespace />todate">
                        </div>
                        <label class="error" for="<portlet:namespace/>todate"></label>
                    </div>
                </div>
                <div class="row">
                    <div class="col pt-3 pb-3">
                        <button id="addRow" class="float-right nps-btn" type="button">Add Row</button>
                    </div>
                </div>
                <input type="hidden" class="rowcount" name="<portlet:namespace />rowcount">
                <table class="table table-bordered table-responsive" id="example">
                    <thead>
                        <tr>
                            <th>TRan Date</th>
                            <th>Chq No</th>
                            <th>Particulars</th>
                            <th>Debit</th>
                            <th>Credit</th>
                            <th>Balance</th>
                            <th>Init.Br.</th>
                        </tr>
                    </thead>
                    <tr>
                        <td></td>
                        <td></td>
                        <th>Opening Balance</th>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><input type="date" class="tRandate form-control" name="<portlet:namespace />trandate1"></td>
                        <td><input type="text" class="chqno form-control" name="<portlet:namespace />chqno1"></td>
                        <td><input type="text" class="particulars form-control" name="<portlet:namespace />particulars1"></td>
                        <td><input type="text" class="debit form-control" name="<portlet:namespace />debit1"></td>
                        <td><input type="text" class="credit form-control" name="<portlet:namespace />credit1"></td>
                        <td><input type="text" class="balance form-control" name="<portlet:namespace />balance1"></td>
                        <td><input type="text" class="initbr form-control" name="<portlet:namespace />initbr1"></td>
                    </tr>
                    <tfoot>
                        <tr>
                            <td></td>
                            <td></td>
                            <th>Transaction Total</th>
                            <td><input type="text" class="todebit form-control" name="<portlet:namespace />todebit"></td>
                            <td><input type="text" class="tocredit form-control" name="<portlet:namespace />tocredit"></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <th colspan="3">Closing Balance</th>
                            <td><input type="text" class="clbalance form-control" name="<portlet:namespace />clbalance"></td>
                            <td><input type="text" class="clinitbr form-control" name="<portlet:namespace />clinitbr"></td>
                        </tr>
                    </tfoot>
                </table>
                		<div class="nps-input-box">
                        	<button id="upload" class="common-btn d-inline-block" name="Submit" type="button" >Save</button>
                           <!-- <a href="javascript:;" class="common-btn d-inline-block">save</a> -->
                        </div>
                    </aui:form>
                </div>
            </div>
        </div>
    </div>
</div> --%>


<script type="text/javascript">
function getreportUploadLogId(){
	var fd = new FormData($("form.form")[0]);
	$.ajax({
        url: '<%=getreportlogdetailsURL %>',  
        type: 'POST',
        data: fd,
        success:function(data){
        	console.log(data);
        	try {
            	data = JSON.parse(data);
            	if(data.status){
            		$("#upload").prop('disabled', false);
            		$(".reportUploadLogId").val(data.reportUploadLogId);
                	
                	//var now = new Date(data.reportDate);
                	//var today = now.getFullYear()+"-"+(now.month)+"-"+(now.day) ;
                	$(".reportDate").val(data.ReportDate);
            	}else{
            		$("#upload").prop('disabled', true);
            	}
            	
            } catch (e) {
            	console.log("error while parsing the json data",e);
            }
        },
        error: function() {
        	//$(".animaion").hide();
        	//toastr.error('An error occured while submitting the form');
       		console.log("Error Occured in ajax call");
        },
        complete: function(){
				console.log("Complete");
	     },
        cache: false,
        contentType: false,
        processData: false
    });
}

$(document).ready(function() {
	
	getreportUploadLogId();
	
	toastr.options = {
	  "debug": false,
	  "positionClass": "toast-bottom-right",
	  "onclick": null,
	  "fadeIn": 300,
	  "fadeOut": 1000,
	  "timeOut": 9000,
	  "extendedTimeOut": 1000
	}
	
	$('#annexure2').bind('change', function () {
		  var filename = $("#annexure2").val();
		  if (/^\s*$/.test(filename)) {
		     $(".file-upload").removeClass('active');
		     $("#noFile1").text("No file chosen...");
		  }
		  else {
		     $(".file-upload").addClass('active');
		     $("#noFile1").text(filename.replace("C:\\fakepath\\", ""));
		  }
		});
	
	
	$.validator.addMethod("lettersonly", function(value, element) {
		  return this.optional(element) || /^[a-zA-Z]+$/i.test(value);
		}, "Please enter characters only"); 

	
	$("form.form").validate({
		  rules: {
			/* <portlet:namespace/>accountname: {
		      required: true,
		      lettersonly: true
		    },
		    <portlet:namespace/>statement: {
			      required: true
			},
			<portlet:namespace/>adressi: {
				required: true
			},
			<portlet:namespace/>adressii: {
				required: true
			},
			<portlet:namespace/>adressiii:{
				required: true
			},
			<portlet:namespace/>adressiv:{
				required: true
			},
			<portlet:namespace/>adressv:{
				required: true
			},
			<portlet:namespace/>pin:{
				required: true,
				digits: true
			},
			<portlet:namespace/>customerno:{
				required: true
			},
			<portlet:namespace/>scheme:{
				required: true
			},
			<portlet:namespace/>curencyinr:{
				required: true,
				lettersonly: true
			},
			<portlet:namespace/>statementacno:{
				required: true
			},
			<portlet:namespace/>formdate:{
				required: true
			},
			<portlet:namespace/>todate:{
				required: true
			},
			<portlet:namespace/>trandate1:{
				required: true
			},
			<portlet:namespace/>chqno1:{
				required: true,
				number: true
			},
			<portlet:namespace/>particulars1:{
				required: true,
				number: true
			},
			<portlet:namespace/>debit1:{
				required: true,
				number: true
			},
			<portlet:namespace/>credit1:{
				required: true,
				number: true
			},
			<portlet:namespace/>balance1:{
				required: true,
				number: true
			},
			<portlet:namespace/>initbr1:{
				required: true,
				number: true
			},
 */			
 			<portlet:namespace/>annexure2:{
				required: true,
			},
		  }
		});
	
	var t = $('#example').DataTable({
    "paging":   false,
    "ordering": false,
    "info":     false,
    "searching": false
    
	});
    var counter = 2;
/*  
    $('#addRow').on( 'click', function () {
    	console.log($('#example'));
    	
    	//var t = $('#example')
    	$(".rowcount").val(counter);
        t.row.add( [
        	'<input type="date" class="tRandate form-control" name="<portlet:namespace />trandate'+counter+'">',
        	'<input type="text" class="chqno form-control" name="<portlet:namespace />chqno'+counter+'">',
			'<input type="text" class="particulars form-control" name="<portlet:namespace />particulars'+counter+'">',
			'<input type="text" class="debit form-control" name="<portlet:namespace />debit'+counter+'">',
			'<input type="text" class="credit form-control" name="<portlet:namespace />credit'+counter+'">',
			'<input type="text" class="balance form-control" name="<portlet:namespace />balance'+counter+'">',
			'<input type="text" class="initbr form-control" name="<portlet:namespace />initbr'+counter+'">'
        ] ).draw( false );
 
        counter++;
        
        $('.tRandate').each(function() {
	        $(this).rules("add", 
	            {
		        	required: true,
	                messages: {
	                    required: "This field is required.",
	                }
	            }
	        );
	    });
        
        $('.chqno').each(function() {
	        $(this).rules("add", 
	            {
		        	required: true,
		        	number: true,
	                messages: {
	                    required: "This field is required.",
	                }
	            }
	        );
	    });
        
        $('.particulars').each(function() {
	        $(this).rules("add", 
	            {
		        	required: true,
		        	number: true,
	                messages: {
	                    required: "This field is required.",
	                }
	            }
	        );
	    });
        
        $('.debit').each(function() {
	        $(this).rules("add", 
	            {
		        	required: true,
		        	number: true,
	                messages: {
	                    required: "This field is required.",
	                }
	            }
	        );
	    });
        
        $('.credit').each(function() {
	        $(this).rules("add", 
	            {
		        	required: true,
		        	number: true,
	                messages: {
	                    required: "This field is required.",
	                }
	            }
	        );
	    });
        
        $('.balance').each(function() {
	        $(this).rules("add", 
	            {
		        	required: true,
		        	number: true,
	                messages: {
	                    required: "This field is required.",
	                }
	            }
	        );
	    });
        
        $('.initbr').each(function() {
	        $(this).rules("add", 
	            {
		        	required: true,
		        	number: true,
	                messages: {
	                    required: "This field is required.",
	                }
	            }
	        );
	    });
        
    } ); */
 
    $(".animaion").hide();
    $('#btn-submit').on('click', function(){ 
/*     	var todebit = parseInt(0);
        $("input.debit")
        	.map(function(){
        		todebit=todebit+parseInt($(this).val());
        		return 0;
        	}).get();
        $(".todebit").val(todebit);
        
        var tocredit = parseInt(0);
        $("input.credit")
        	.map(function(){
        		tocredit=tocredit+parseInt($(this).val());
        		return 0;
        	}).get();
        $(".tocredit").val(tocredit);
        
        var clbalance = parseInt(0);
        $("input.balance")
        	.map(function(){
        		clbalance=clbalance+parseInt($(this).val());
        		return 0;
        	}).get();
        $(".clbalance").val(clbalance);
        
        var clinitbr = parseInt(0);
        $("input.initbr")
        	.map(function(){
        		clinitbr=clinitbr+parseInt($(this).val());
        		return 0;
        	}).get();
        $(".clinitbr").val(clinitbr); */
        if ($('input[name="annexure2"]').get(0).files.length === 0) {
    	    console.log("No files selected.");
    	    $("#error1").html("Please select a file to upload");
    	    return false;
    	}
        
    	if($("form.form").valid()){
	        var fd = new FormData($("form.form")[0]);
	        $(".content").hide();
	        $(".animaion").show();
	        $.ajax({
	            url: '<%=accountStatementUrl %>',  
	            type: 'POST',
	            data: fd,
	            cache: false,
	            contentType: false,
	            processData: false,
	            success:function(data){
	            	console.log("Inside Success");
	            	$(".content").show();
	                $(".animaion").hide();
	                $('#success_tic').modal('show');
              		//toastr.success('Form has been submitted successfully!');
              		//$("form.form")[0].reset();
              		//$('#output').html("Data submited successfuly.");
	            },
	            error: function() {
	           		console.log("Error Occured in ajax call");
	           		$(".animaion").hide();
	           		//toastr.error('An error occured while submitting the form');
	           		$('#output').html("An error occourd while submitting the form.");
            		$('#errorExcel').modal('show');
            		
	            },
	            complete: function(){
	            	$(".animaion").hide();
		        }
	        });
    	}else{
    		toastr.error('Please fill the required field(s).');
    		//$('#output').html("Please fill the required field.");	
   		}
    });
    $('#success_tic').on('hidden.bs.modal', function (e) {
		location.reload(); 
	})
    $('#errorExcel').on('hidden.bs.modal', function (e) {
		location.reload(); 
	})
	
});

</script>