create table DailyAverage (
	id_ LONG not null primary key,
	CustomerId LONG,
	NPSAcNumber LONG,
	NPSAcName VARCHAR(75) null,
	TranDate DATE null,
	TranId LONG,
	PartTranSrNo LONG,
	ChqNo LONG,
	ChqDate DATE null,
	DrTxn DOUBLE,
	CrTxn DOUBLE,
	RunningBalance DOUBLE,
	TranNarPart VARCHAR(75) null,
	TransactionRemarks VARCHAR(75) null,
	InitiatingSOLId LONG,
	CounterPartyAcNumber VARCHAR(75) null
);

create table consolidated_Financial3  (
	id_ LONG not null primary key,
	reportUploadLogId LONG,
	sheet_name VARCHAR(75) null,
	as_on_date VARCHAR(75) null,
	pension_fund_name VARCHAR(75) null,
	scheme_name VARCHAR(75) null,
	sl_no VARCHAR(75) null,
	particulars VARCHAR(75) null,
	schedule VARCHAR(75) null,
	current_year VARCHAR(75) null,
	previous_year VARCHAR(75) null,
	createdate DATE null,
	createdby LONG
);

create table consolidated_financial1  (
	id_ LONG not null primary key,
	reportUploadLogId LONG,
	sheet_name VARCHAR(75) null,
	as_on_date VARCHAR(75) null,
	pension_fund_name VARCHAR(75) null,
	sl_no VARCHAR(75) null,
	particulars VARCHAR(75) null,
	schedule VARCHAR(75) null,
	current_year VARCHAR(75) null,
	previous_year VARCHAR(75) null,
	createdate DATE null,
	createdby LONG
);

create table consolidated_financial2  (
	id_ LONG not null primary key,
	reportUploadLogId LONG,
	sheet_name VARCHAR(75) null,
	as_on_date VARCHAR(75) null,
	pension_fund_name VARCHAR(75) null,
	scheme_name VARCHAR(75) null,
	sl_no VARCHAR(75) null,
	particulars VARCHAR(75) null,
	current_year VARCHAR(75) null,
	previous_year VARCHAR(75) null,
	createdate DATE null,
	createdby LONG
);

create table consolidated_financial4  (
	id_ LONG not null primary key,
	reportUploadLogId LONG,
	sheet_name VARCHAR(75) null,
	as_on_date VARCHAR(75) null,
	pension_fund_name VARCHAR(75) null,
	scheme_name VARCHAR(75) null,
	sl_no VARCHAR(75) null,
	particulars VARCHAR(75) null,
	schedule VARCHAR(75) null,
	current_year VARCHAR(75) null,
	previous_year VARCHAR(75) null,
	remark VARCHAR(75) null,
	createdate DATE null,
	createdby LONG
);

create table votematrixpfm (
	id_ LONG not null primary key,
	meeting_date VARCHAR(75) null,
	isin VARCHAR(75) null,
	company_name VARCHAR(75) null,
	meeting_type VARCHAR(75) null,
	resolution_category VARCHAR(75) null,
	resolution_dtls VARCHAR(75) null,
	resolution_type VARCHAR(75) null,
	lic_vote VARCHAR(75) null,
	lic_rationale_vote_recomm VARCHAR(75) null,
	lic_shares_held VARCHAR(75) null,
	uti_vote VARCHAR(75) null,
	uti_rationale_vote_recomm VARCHAR(75) null,
	uti_shares_held VARCHAR(75) null,
	sbi_vote VARCHAR(75) null,
	sbi_rationale_vote_recomm VARCHAR(75) null,
	sbi_shares_held VARCHAR(75) null,
	hdfc_vote VARCHAR(75) null,
	hdfc_rationale_vote_recomm VARCHAR(75) null,
	hdfc_shares_held VARCHAR(75) null,
	icici_vote VARCHAR(75) null,
	icici_rationale_vote_recomm VARCHAR(75) null,
	icici_shares_held VARCHAR(75) null,
	kotak_vote VARCHAR(75) null,
	kotak_rationale_vote_recomm VARCHAR(75) null,
	kotak_shares_held VARCHAR(75) null,
	birla_vote VARCHAR(75) null,
	birla_rationale_vote_recomm VARCHAR(75) null,
	birla_shares_held VARCHAR(75) null,
	total_shareholding_nps_comb VARCHAR(75) null,
	per_of_total_shares_held_comb VARCHAR(75) null,
	majority_vote_pfm_combined VARCHAR(75) null,
	ses_vote_recomm VARCHAR(75) null,
	ses_rationale_vote_recomm VARCHAR(75) null,
	per_of_total_shares_held_prom VARCHAR(75) null,
	votes_polled_promoter VARCHAR(75) null,
	votes_in_favor_promoter VARCHAR(75) null,
	votes_in_against_promoter VARCHAR(75) null,
	per_of_total_shares_held_inst VARCHAR(75) null,
	votes_polled_inst VARCHAR(75) null,
	votes_in_favor_inst VARCHAR(75) null,
	votes_in_against_inst VARCHAR(75) null,
	per_of_total_shares_held_ret VARCHAR(75) null,
	votes_polled_retail VARCHAR(75) null,
	votes_in_favor_retail VARCHAR(75) null,
	votes_in_against_retail VARCHAR(75) null,
	votes_polled VARCHAR(75) null,
	for_ VARCHAR(75) null,
	against VARCHAR(75) null,
	outcome VARCHAR(75) null,
	ses_report VARCHAR(75) null,
	iias_vote_recomm VARCHAR(75) null,
	iias_rationale_vote_recomm VARCHAR(75) null,
	divergence_pf_vs_ses VARCHAR(75) null,
	divergence_pf_vs_iias VARCHAR(75) null,
	divergence_ses_vs_iias VARCHAR(75) null,
	div_pfm_vs_both_proxy_adv VARCHAR(75) null,
	createdate DATE null,
	createdby LONG
);