DROP TABLE IF EXISTS "bm_cgms_agenda_lastinfo";
DROP SEQUENCE IF EXISTS bm_cgms_agenda_lastinfo_id__seq1;
CREATE SEQUENCE bm_cgms_agenda_lastinfo_id__seq1 INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE public.bm_cgms_agenda_lastinfo (
    id_ bigint NOT NULL,
    date_5 character varying(10),
    number_of_griev_1 character varying(50),
    number_of_griev_2 character varying(50),
    number_of_griev_3 character varying(50),
    number_of_griev_4 character varying(50),
    number_of_griev_5 character varying(50),
    number_of_griev_6 character varying(50),
    grievances_1 character varying(50),
    grievances_2 character varying(50),
    grievances_3 character varying(50),
    grievances_4 character varying(50),
    grievances_5 character varying(50),
    grievances_6 character varying(50),
    grievances_7 character varying(50),
    grievances_8 character varying(50),
    grievances_9 character varying(50),
    grievances_10 character varying(50),
    grievances_11 character varying(50),
    grievances_12 character varying(50),
    grievances_13 character varying(50),
    grievances_14 character varying(50),
    grievances_15 character varying(50),
    grievances_16 character varying(50),
    grievances_17 character varying(50),
    grievances_18 character varying(50),
    grievances_19 character varying(50),
    grievances_20 character varying(50),
    grievances_21 character varying(50),
    grievances_22 character varying(50),
    grievances_23 character varying(50),
    grievances_24 character varying(50),
    grievances_25 character varying(50),
    grievances_26 character varying(50),
    grievances_27 character varying(50),
    grievances_28 character varying(50),
    grievances_29 character varying(50),
    grievances_30 character varying(50),
    activity character varying(50),
    grievances_31 character varying(50),
    grievances_32 character varying(50),
    pfrda_policy character varying(50),
    date_6 character varying(50),
    date_7 date,
    createdon date,
    createdby bigint,
    CONSTRAINT bm_cgms_agenda_lastinfo_pkey PRIMARY KEY (id_)
)WITH (oids = false);