DROP TABLE IF EXISTS "compcert";
DROP SEQUENCE IF EXISTS compcert_compid_seq;
CREATE SEQUENCE compcert_compid_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE public.compcert (
    compid integer DEFAULT nextval('public.compcert_compid_seq'::regclass) NOT NULL,
    certnumber character varying(20),
    compliancedate date,
    compfyendingdate date,
    tbfyendingdate date,
    tbpfrdacomp character varying(20),
    tbpfrdarem character varying(255),
    tbreviewcomp character varying(20),
    tbreviewrem character varying(255),
    tbinvestcomp character varying(20),
    tbinvestrem character varying(255),
    tbcommcomp character varying(20),
    tbcommrem character varying(255),
    tbsubmitcomp character varying(20),
    tbsubmitrem character varying(255),
    tbobservecomp character varying(20),
    tbobserverem character varying(255),
    tbsubscribecomp character varying(20),
    tbsubscriberem character varying(255),
    maauditorscomp character varying(20),
    maauditorsrem character varying(255),
    macompliancecomp character varying(20),
    macompliancerem character varying(255),
    maobservecomp character varying(20),
    maobserverem character varying(255),
    moagreecomp character varying(20),
    moagreerem character varying(255),
    mofoundcomp character varying(20),
    mofoundrem character varying(255),
    mosegcomp character varying(20),
    mosegrem character varying(255),
    modilicomp character varying(20),
    modilirem character varying(255),
    pacustodycomp character varying(20),
    pacustodyrem character varying(255),
    paprotectedcomp character varying(20),
    paprotectedrem character varying(255),
    pasupervisecomp character varying(20),
    pasuperviserem character varying(255),
    paaccountscomp character varying(20),
    paaccountsrem character varying(255),
    ntomaintaincomp character varying(20),
    ntomaintainrem character varying(255),
    ntoadequatecomp character varying(20),
    ntoadequaterem character varying(255),
    ntoinformcomp character varying(20),
    ntoinformrem character varying(255),
    ntogrievancescomp character varying(20),
    ntogrievancesrem character varying(255),
    ntoexitcomp character varying(20),
    ntoexitrem character varying(255),
    aaannualcomp character varying(20),
    aaannualrem character varying(255),
    aabookscomp character varying(20),
    aabooksrem character varying(255),
    aaquarterlycomp character varying(20),
    aaquarterlyrem character varying(255),
    aarulescomp character varying(20),
    aarulesrem character varying(255),
    compofficername1 character varying(20),
    signdate1 date,
    place1 character varying(20),
    compofficername2 character varying(20),
    signdate2 date,
    place2 character varying(20),
	uuid_ character varying(75),
    createdby bigint,
    createdate timestamp without time zone,
    modifyby bigint,
    modifydate timestamp without time zone,
    status integer,
    statusbyuserid bigint,
    statusbyusername character varying(75),
    statusdate timestamp without time zone
)WITH (oids = false);