DROP TABLE IF EXISTS mn_comp_certificate;

CREATE TABLE public.mn_comp_certificate (
    reportuploadlogid bigint NOT NULL,
	reportmasterid bigint,
	reportdate date,
	fileentryid bigint,
	date_1 date,
	purchase_of_securities character varying,
	Purchase_of_sec_rem_1_1_2 character varying,
	detailed_investment character varying,
	purchase_of_sec_rem_1_2a_2 character varying,
	investments_approved character varying,
	purchase_of_sec_rem_1_2b_2 character varying,
	decision_of_investment character varying,
	purchase_of_sec_rem_1_2c_2 character varying,
	investments_non_dematerialized character varying,
	purchase_of_sec_rem_1_2d_2 character varying,
	all_investments_from_funds character varying,
	purchase_of_sec_rem_1_2e_2 character varying,
	delivery_of_securities_purch character varying,
	purchase_of_sec_rem_1_3_2 character varying,
	investment_done_in_ipo character varying,
	purchase_of_secu_rem_1_4_2 character varying,
	scheme_investments character varying,
	securities_held_2_1_2 character varying,
	stop_loss_trigger character varying,
	securities_held_2_2a_2 character varying,
	decision_approved_by_committee character varying,
	securities_held_2_2b_2 character varying,
	decision_properly_documented character varying,
	securities_held_2_2c_2 character varying,
	inter_scheme_transfer character varying,
	securities_held_2_3_2 character varying,
	investment_held_in_equity character varying,
	securities_held_2_4_2 character varying,
	investment_in_equity_shares character varying,
	securities_held_2_5_2 character varying,
	disinvestments_approved character varying,
	sale_of_securities_3_1a_2 character varying,
	decision_of_disinvestment character varying,
	sale_of_securities_3_1b_2 character varying,
	delivery_of_securities_sale character varying,
	sale_of_securities_3_2_2 character varying,
	all_investment_charges character varying,
	reports_and_disclosure_4_1a_2 character varying,
	pfm_adhered character varying,
	reports_and_disclosure_4_1b_2 character varying,
	records_of_the_audit_of_nav character varying,
	reports_and_disclosure_4_1c_2 character varying,
	scheme_wise_nav_uploaded character varying,
	reports_and_disclosure_4_1d_2 character varying,
	scheme_wise_nav_submitted character varying,
	reports_and_disclosure_4_1e_2 character varying,
	monthly_reports_submitted character varying,
	reports_and_disclosure_4_2a_2 character varying,
	scrip_wise_details character varying,
	reports_and_disclosure_4_2b_2 character varying,
	date_2 character varying,
	company_name character varying,
	emplolyee_name character varying,
	roles character varying,
	date_3 date,
	place character varying,
	annexure_a_i bigint,
	annexure_a_ii bigint,
	annexure_b bigint,
	annexure_c bigint,
	annexure_d bigint,
	annexure_e bigint,
	annexure_f bigint,
	annexure_g bigint,
	annexure_h bigint,
	
	
    createdon timestamp,
    createdby bigint,
	modifyby bigint,
    modifydate timestamp,
    status integer,
    statusbyuserid bigint,
    statusbyusername character varying,
    statusdate timestamp,
    uuid_ character varying,
    workflowcontext text,
	remarks text
)WITH (oids = false);