DROP TABLE IF EXISTS "mn_ses_vote_matrix";
DROP SEQUENCE IF EXISTS mn_ses_vote_matrix_id__seq1;
CREATE SEQUENCE mn_ses_vote_matrix_id__seq1 INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE public.mn_ses_vote_matrix (
    id_ bigint NOT NULL,
    meeting_date date,
    isin character varying,
    company_name character varying,
    meeting_type character varying,
    resolution_category character varying,
    resol_dtls character varying,
    resol_type character varying,
    lic_vote character varying,
    lic_rationale_vote_recomm character varying,
    lic_shares_held bigint,
    uti_vote character varying,
    uti_rationale_vote_recomm character varying,
    uti_shares_held bigint,
    sbi_vote character varying,
    sbi_rationale_vote_recomm character varying,
    sbi_shares_held bigint,
    hdfc_vote character varying,
    hdfc_rationale_vote_recomm character varying,
    hdfc_shares_held bigint,
    icici_vote character varying,
    icici_rationale_vote_recomm character varying,
    icici_shares_held bigint,
    kotak_vote character varying,
    kotak_rationale_vote_recomm character varying,
    kotak_shares_held bigint,
    birla_vote character varying,
    birla_rationale_vote_recomm character varying,
    birla_shares_held bigint,
    total_sharehldng_nps_comb numeric(20,2),
    prcnt_total_shares_held_comb character varying,
    majority_vote_pfm_comb character varying,
    ses_vote_recomm character varying,
    ses_rationale_vote_recomm character varying,
    prcnt_tot_shares_held_promoter character varying,
    votes_polled_promoter character varying,
    votes_in_favor_promoter character varying,
    votes_in_against_promoter character varying,
    prcnt_tot_shares_held_institut character varying,
    votes_polled_institution character varying,
    votes_in_favor_insttitution character varying,
    votes_in_against_institution character varying,
    prcnt_total_shares_held_retail character varying,
    votes_polled_retail character varying,
    votes_in_favor_retail character varying,
    votes_in_against_retail character varying,
    votes_polled_voting_outcome character varying,
    voting_for character varying,
    voting_against character varying,
    outcome character varying,
    ses_report character varying,
    createdon date,
    createdby bigint,
    reportuploadlogid bigint,
    CONSTRAINT mn_ses_vote_matrix_pkey PRIMARY KEY (id_)
)WITH (oids = false);