DROP TABLE IF EXISTS "qr_quarterly_vote_matrix";
DROP SEQUENCE IF EXISTS qr_quarterly_vote_matrix_id__seq1;
CREATE SEQUENCE qr_quarterly_vote_matrix_id__seq1 INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE IF NOT EXISTS public.qr_quarterly_vote_matrix
(
    id_ bigint NOT NULL,
    meeting_date date,
	isin character varying(1000),
	company_name character varying,	
	meeting_type character varying,
	resolution_category character varying,
	resolution_dtls character varying,
	resolution_type character varying,
	lic_vote character varying,
	lic_rationale_vote_recomm character varying,
	lic_shares_held numeric(15,2),
	uti_vote character varying,
	uti_rationale_vote_recomm character varying,
	uti_shares_held numeric(15,2),
	sbi_vote character varying,
	sbi_rationale_vote_recomm character varying ,
	sbi_shares_held numeric(15,2),
	hdfc_vote character varying,
	hdfc_rationale_vote_recomm character varying,
	hdfc_shares_held numeric(15,2),
	icici_vote character varying,
	icici_rationale_vote_recomm character varying,
	icici_shares_held numeric(15,2),
	kotak_vote character varying,
	kotak_rationale_vote_recomm character varying,
	kotak_shares_held numeric(15,2),
	birla_vote character varying,
	birla_rationale_vote_recomm character varying,
	birla_shares_held numeric(15,2),
	total_shareholding_nps_comb numeric(15,2),
	prcnt_total_shares_held_comb numeric(15,2),
	majority_vote_pfm_combined character varying,
	ses_vote_recomm character varying,
	ses_rationale_vote_recomm character varying,
	pr_of_total_shares_held_prom numeric(15,2),
	votes_polled_promoter numeric(15,2),
	votes_in_favor_promoter numeric(15,2),
	votes_in_against_promoter numeric(15,2),
	prcnt_total_shares_held_inst numeric(15,2),
	votes_polled_inst numeric(15,2),
	votes_in_favor_inst numeric(15,2),
	votes_in_against_inst numeric(15,2),
	prcnt_total_shares_held_retail numeric(15,2),
	votes_polled_retail numeric(15,2),
	votes_in_favor_retail numeric(15,2),
	votes_in_against_retail numeric(15,2),
	votes_polled numeric(15,2),
	for_ numeric(15,2),
	against numeric(15,2),
	outcome character varying,
	ses_report character varying,
    createdate date,
    createdby bigint,
    CONSTRAINT qr_quarterly_vote_matrix_pkey PRIMARY KEY (id_)
) WITH (oids = false);