CREATE TABLE public.quarterlyauditor (
    id integer NOT NULL,
    performantdate date,
    bankname character varying(100),
    numberofcases character varying(100),
    amount character varying(100),
    listofamountdate date,
    companyname character varying(50),
    designation character varying(50),
    regno character varying(50),
    partnercompanyname character varying(50),
    partnermemno character varying(50),
    submitdate date,
    place character varying(100),
    uuid_ character varying(75),
    createdby bigint,
    createdate timestamp without time zone,
    modifyby bigint,
    modifydate timestamp without time zone,
    status integer,
    statusbyuserid bigint,
    statusbyusername character varying(75),
    statusdate timestamp without time zone
);
