DROP TABLE IF EXISTS "quarterlyinterval";
CREATE TABLE "public"."quarterlyinterval" (
    "reportuploadlogid" integer NOT NULL,
    "formdate" date,
    "oneia" character varying,
    "oneib" character varying,
    "oneiia" character varying,
    "oneiib" character varying,
    "oneiic" character varying,
    "oneiid" character varying,
    "oneiiia" character varying,
    "oneiiib" character varying,
    "oneiva" character varying,
    "onev" character varying,
    "twoia" character varying,
    "twoib" character varying,
    "twoic" character varying,
    "twoiione" character varying,
    "twoiitwo" character varying,
    "twoiithree" character varying,
    "twoiifour" character varying,
    "twoiifive" character varying,
    "twoiisix" character varying,
    "twoiiseven" character varying,
    "threea" character varying,
    "threeb" character varying,
    "threec" character varying,
    "threeci" character varying,
    "threecii" character varying,
    "threeciii" character varying,
    "threeciv" character varying,
    "foura" character varying,
    "fourb" character varying,
    "fourc" character varying,
    "fivei" character varying,
    "fiveii" character varying,
    "fiveiii" character varying,
    "fiveiv" character varying,
    "fiveva" character varying,
    "fivevb" character varying,
    "fivevc" character varying,
    "fivevia" character varying,
    "fivevib" character varying,
    "sixi" character varying,
    "sixiia" character varying,
    "sixiib" character varying,
    "sixiic" character varying,
    "sevenia" character varying,
    "sevenib" character varying,
    "sevenic" character varying,
    "sevenid" character varying,
    "sevenie" character varying,
    "eightia" character varying,
    "eightib" character varying,
    "eightii" character varying,
    "eightiii" character varying,
    "eightiv" character varying,
    "eightv" character varying,
    "eightvia" character varying,
    "eightvib" character varying,
    "eightviia" character varying,
    "eightviib" character varying,
    "eightviii" character varying,
    "ninea" character varying,
    "nineb" character varying,
    "ten" character varying,
    "elevena" character varying,
    "elevenb" character varying,
    "twelve" character varying,
    "notedate" character varying,
    "companies" character varying,
    "date_3" character varying,
    "place" character varying,
    "ceoname" character varying,
    "ceonameii" character varying,
    "board_a" character varying,
    "board_b" character varying,
    "investment_a" character varying,
    "investment_b" character varying,
    "risk_a" character varying,
    "risk_b" character varying,
    "annex_ii" character varying,
    "annex_iii" character varying,
    "annex_iv" character varying,
    "reportmasterid" bigint,
    "reportdate" date,
    "createdate" timestamp,
    "createdby" bigint,
    "modifyby" bigint,
    "modifydate" date,
    "status" integer,
    "statusbyuserid" bigint,
    "statusbyusername" character varying,
    "statusdate" timestamp,
    "uuid_" character varying,
    "workflowcontext" character varying,
    "remarks" character varying,
    "annex_comp_certificate" bigint
) WITH (oids = false);