DROP TABLE IF EXISTS "scrutinyquarterlyinterval";
CREATE TABLE "public"."scrutinyquarterlyinterval" (
    "id_" integer NOT NULL,
    "reportuploadlogid" bigint,
    "username" character varying,
    "version" numeric,
    "userid" bigint,
    "oneia_rem" character varying,
    "oneib_rem" character varying,
    "oneiia_rem" character varying,
    "oneiib_rem" character varying,
    "oneiic_rem" character varying,
    "oneiid_rem" character varying,
    "oneiiia_rem" character varying,
    "oneiiib_rem" character varying,
    "oneiva_rem" character varying,
    "onev_rem" character varying,
    "twoia_rem" character varying,
    "twoib_rem" character varying,
    "twoic_rem" character varying,
    "twoiione_rem" character varying,
    "twoiitwo_rem" character varying,
    "twoiithree_rem" character varying,
    "twoiifour_rem" character varying,
    "twoiifive_rem" character varying,
    "twoiisix_rem" character varying,
    "twoiiseven_rem" character varying,
    "threea_rem" character varying,
    "threeb_rem" character varying,
    "threec_rem" character varying,
    "threeci_rem" character varying,
    "threecii_rem" character varying,
    "threeciii_rem" character varying,
    "threeciv_rem" character varying,
    "foura_rem" character varying,
    "fourb_rem" character varying,
    "fourc_rem" character varying,
    "fivei_rem" character varying,
    "fiveii_rem" character varying,
    "fiveiii_rem" character varying,
    "fiveiv_rem" character varying,
    "fiveva_rem" character varying,
    "fivevb_rem" character varying,
    "fivevc_rem" character varying,
    "fivevia_rem" character varying,
    "fivevib_rem" character varying,
    "sixi_rem" character varying,
    "sixiia_rem" character varying,
    "sixiib_rem" character varying,
    "sixiic_rem" character varying,
    "sevenia_rem" character varying,
    "sevenib_rem" character varying,
    "sevenic_rem" character varying,
    "sevenid_rem" character varying,
    "sevenie_rem" character varying,
    "eightia_rem" character varying,
    "eightib_rem" character varying,
    "eightii_rem" character varying,
    "eightiii_rem" character varying,
    "eightiv_rem" character varying,
    "eightv_rem" character varying,
    "eightvia_rem" character varying,
    "eightvib_rem" character varying,
    "eightviia_rem" character varying,
    "eightviib_rem" character varying,
    "eightviii_rem" character varying,
    "ninea_rem" character varying,
    "nineb_rem" character varying,
    "ten_rem" character varying,
    "elevena_rem" character varying,
    "elevenb_rem" character varying,
    "twelve_rem" character varying,
    "board_a_rem" character varying,
    "board_b_rem" character varying,
    "investment_a_rem" character varying,
    "investment_b_rem" character varying,
    "risk_a_rem" character varying,
    "risk_b_rem" character varying,
    "annex_ii_rem" character varying,
    "annex_iii_rem" character varying,
    "annex_iv_rem" character varying,
    "createdate" date,
    "createdby" bigint,
    "annex_comp_certificate_rem" character varying NOT NULL
) WITH (oids = false);