DROP TABLE IF EXISTS "weekly_repo_noneq_cbv";
DROP SEQUENCE IF EXISTS weekly_repo_noneq_cbv_id__seq1;
CREATE SEQUENCE weekly_repo_noneq_cbv_id__seq1 INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE public.weekly_repo_noneq_cbv (
    id_ bigint NOT NULL,
    date_ date,
    fin character varying(50),
    scheme character varying(100),
    company_name character varying(200),
    security_code character varying(40),
    isin character varying(40),
    secdesc character varying(200),
    sec character varying(40),
    coupon character varying(40),
    faceval numeric(15,2),
    custhold bigint,
    transit bigint,
    loghold bigint,
    price numeric(15,4),
    source_ character varying(40),
    value_ numeric(15,4),
    tradedate date,
    method_ character varying(40),
    gross_price numeric(15,3),
    accured_interest numeric(15,4),
    modified_duration numeric(15,8),
    ytm numeric(15,4),
    nse_price numeric(15,3),
    tenor_in_years numeric(15,9),
    value_of_security character varying(40),
    issuerclass character varying(40),
    coupontype character varying(100),
    couponpaymentfrequency int,
    allotmentdate date,
    firstipdate date,
    lastipdate date,
    finalredemptiondate date,
    redemppremium character varying(40),
    rating character varying(40),
    illiquiditydiscount character varying(40),
    higherrating character varying(40),
    ptc_amort_method character varying(40),
    coupon_form character varying(40),
    compounding_frequency character varying(40),
    matrix_type character varying(40),
    sector character varying(100),
    call_date date,
    put_date date,
    settlement_date date,
    benchmark_date date,
    conversion_date date,
    goi_serviced character varying(40),
    secured_unsecured character varying,
    createdon date,
    createdby bigint,
    reportuploadlogid bigint,
    CONSTRAINT weekly_repo_noneq_cbv_pkey PRIMARY KEY (id_)
)WITH (oids = false);